spring:
  application:
    name: GRAPHQL-SPRINGBOOT
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1



graphql:
  servlet:
    max-query-depth: 100
    exception-handlers-enabled: true
    tracing-enabled: true
  playground:
    enabled: true
    headers:
      Authorization: Bearer Token
      user_id: jos
    tabs:
      - name: Bank Account Graphql
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
server:
  tomcat:
    max-swallow-size: -1

logging:
  pattern:
    console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n%wEx