spring:
  application:
    name: GRAPHQL-SPRINGBOOT

graphql:
  servlet:
    max-query-depth: 100
    exception-handlers-enabled: true
  playground:
    #enabled: false
    headers:
      Authorization: Bearer Token
    tabs:
      - name: Bank Account Graphql
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json
